# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaba7eb4a1580b42f613c3c6b9b21314b100c8c2419ed11e1ad1c4e2669b7242835bc2205569465799ca549a80eadc0ccecafea1e00b684d18fa4318292cf023

test:
  secret_key_base: 8b82686c950ef7229be4b23cc5aa34f0d9a6a25ff522c228ae863a3c656921df30a605a122cb9c357a1dbde56b9fd7af5d17240e555e298748cdd8f21b55aaf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
